apiVersion: v1
kind: Service
metadata:
  name: {{ template "fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ template "name" . }}
spec:
  selector:
    app: {{ template "name" . }}
  ports:
  - port: 80
    protocol: TCP